services:
  postgres-db:
    image: postgres:16
    container_name: core_postgres
    restart: unless-stopped
    ports:
      - '5433:5432' # Shifted to 5433 to avoid clashing with order-service!
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?Set DB_PASSWORD in backend/.env}
      - POSTGRES_DB=${DB_DATABASE:-myfirst} # Docker automatically creates this single DB!
    volumes:
      - core_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379' # Shifted to 6380
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli', 'ping']
      interval: 10s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - '5673:5672' # Shifted to 5673
      - '15673:15672' # Shifted the UI to 15673
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      retries: 10

  core-service:
    build: .
    image: quickbite-core-service:latest
    env_file:
      - .env
    environment:
      - DB_HOST=postgres-db
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    ports:
      - '3000:3000' # Shifted Windows port to 4001, assuming NestJS still runs on 4000 inside
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  core_pg_data:
