import { Injectable, Inject } from '@nestjs/common';
import { Knex } from 'knex';
import { Branch } from '../entity/branch.entity'; // Adjust path if needed

const BRANCH_COLUMNS = [
  'id',
  'restaurant_id',
  'country_code',
  'address_text',
  'label',
  'lat',
  'lng',
  'is_active',
  'opens_at',
  'closes_at',
  'accept_orders',
  'created_at',
  'updated_at',
  'delivery_radius',
  'currency',
  'commission',
  'location',
];

@Injectable()
export class BranchRepository {
  // 1. Inject Knex connection instead of global import
  constructor(@Inject('KNEX_CONNECTION') private readonly knex: Knex) {}

  // 2. Make toEntity a private class method
  private toEntity(row: any): Branch {
    return new Branch({
      id: row.id,
      restaurantId: row.restaurant_id,
      countryCode: row.country_code,
      addressText: row.address_text,
      label: row.label,
      lat: row.lat,
      lng: row.lng,
      isActive: row.is_active,
      opensAt: row.opens_at,
      closesAt: row.closes_at,
      acceptOrders: row.accept_orders,
      createdAt: row.created_at,
      updatedAt: row.updated_at,
      deliveryRadius: row.delivery_radius,
      currency: row.currency,
      commission: row.commission,
      location: row.location,
    });
  }

  // 3. Safe NestJS Transaction Pattern
  async createBranch(
    data: Partial<Branch>,
    trx?: Knex.Transaction,
  ): Promise<Branch> {
    const db = trx || this.knex;

    const [row] = await db('restaurant_branches')
      .insert({
        restaurant_id: data.restaurantId,
        country_code: data.countryCode,
        address_text: data.addressText,
        label: data.label,
        lat: data.lat,
        lng: data.lng,
        is_active: data.isActive ?? true, // Good practice to fallback to true
        opens_at: data.opensAt,
        closes_at: data.closesAt,
        accept_orders: data.acceptOrders ?? true,
        delivery_radius: data.deliveryRadius,
        currency: data.currency,
        commission: data.commission,
        // ✨ Removed created_at and updated_at because defaultTo(knex.fn.now()) handles it!
        // ✨ Location is auto-generated by the DB per your brilliant migration!
      })
      .returning(BRANCH_COLUMNS);

    return this.toEntity(row);
  }

  // 4. The PostGIS Query!
  // Note: I changed the return type to Promise<any[]> because this query returns
  // joined data (r.name, r.logo_url). If you map this through toEntity(), you lose the restaurant data!
  async findNearbyBranches(lat: number, lng: number): Promise<any[]> {
    const result = await this.knex.raw(
      `
       SELECT 
         b.id,
         b.restaurant_id,
         b.address_text,
         b.label,
         b.lat,
         b.lng,
         b.is_active,
         b.accept_orders,
         b.currency,
         r.name as restaurant_name, -- Aliased for clarity
         r.logo_url as restaurant_logo_url -- Aliased for clarity
       FROM restaurant_branches b 
       JOIN restaurants r ON b.restaurant_id = r.id
       WHERE b.is_active = true 
         AND r.status = 'active'
         AND ST_DWithin(b.location, ST_MakePoint(?, ?)::geography, b.delivery_radius * 1000)
    `,
      [lng, lat],
    ); // 🌟 Lng first, Lat second!

    return result.rows.map((row: any) => ({
      id: row.id,
      restaurantId: Number(row.restaurant_id), // Good practice to ensure it's a number
      addressText: row.address_text,
      label: row.label,
      // Postgres returns decimals as strings to prevent JS float precision loss.
      // We convert them back to numbers for the frontend map markers.
      lat: Number(row.lat),
      lng: Number(row.lng),
      isActive: row.is_active,
      acceptOrders: row.accept_orders,
      currency: row.currency,
      restaurantName: row.restaurant_name,
      restaurantLogoUrl: row.restaurant_logo_url,
    }));
  }
  // 📍 Helper to find a single branch
  async findById(id: number): Promise<Branch | null> {
    const row = await this.knex('restaurant_branches').where('id', id).first();
    if (!row) return null;
    return this.toEntity(row);
  }

  // 📍 GET /restaurants/:restaurantId/branches
  async findBranchesByRestaurant(restaurantId: number): Promise<Branch[]> {
    const rows = await this.knex('restaurant_branches').where(
      'restaurant_id',
      restaurantId,
    );

    // We reuse your brilliant private toEntity() mapper to convert to camelCase!
    return rows.map((row) => this.toEntity(row));
  }

  // 📍 PATCH /branches/:id (Owner/Admin)
  async updateBranch(id: number, data: Partial<any>): Promise<Branch> {
    // Map camelCase DTO back to snake_case for the database
    const updateData: any = { updated_at: this.knex.fn.now() };

    if (data.label !== undefined) updateData.label = data.label;
    if (data.addressText !== undefined)
      updateData.address_text = data.addressText;
    if (data.lat !== undefined) updateData.lat = data.lat;
    if (data.lng !== undefined) updateData.lng = data.lng;
    if (data.opensAt !== undefined) updateData.opens_at = data.opensAt;
    if (data.closesAt !== undefined) updateData.closes_at = data.closesAt;
    if (data.deliveryRadius !== undefined)
      updateData.delivery_radius = data.deliveryRadius;
    if (data.currency !== undefined) updateData.currency = data.currency;
    if (data.acceptOrders !== undefined)
      updateData.accept_orders = data.acceptOrders;

    const [updatedRow] = await this.knex('restaurant_branches')
      .where('id', id)
      .update(updateData)
      .returning('*');

    return this.toEntity(updatedRow);
  }

  // 📍 PATCH /branches/:id/status (Admin Only)
  async updateBranchStatus(
    id: number,
    data: { isActive?: boolean; commission?: number },
  ) {
    const updateData: any = { updated_at: this.knex.fn.now() };

    if (data.isActive !== undefined) updateData.is_active = data.isActive;
    if (data.commission !== undefined) updateData.commission = data.commission;

    const [updatedRow] = await this.knex('restaurant_branches')
      .where('id', id)
      .update(updateData)
      .returning(['id', 'is_active', 'accept_orders', 'commission']);

    // Return the exact shape requested
    return {
      id: updatedRow.id,
      isActive: updatedRow.is_active,
      acceptOrders: updatedRow.accept_orders,
      commission: Number(updatedRow.commission),
    };
  }
  async verifyBranchesBelongToRestaurant(
    branchIds: number[],
    restaurantId: number,
    trx?: Knex.Transaction,
  ): Promise<boolean> {
    const db = trx || this.knex;

    const result = await db('restaurant_branches')
      .whereIn('id', branchIds)
      .andWhere('restaurant_id', restaurantId)
      .count('id as count')
      .first();

    // If the count of found branches exactly matches the length of the array they sent,
    // it means 100% of the branches belong to their restaurant.
    const foundCount = Number(result?.count || 0);
    return foundCount === branchIds.length;
  }
}
